# buildspec file for terraform init

version : 0.2

env:
  variables:
    CODE_SRC_DIR: "."

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - "yum install -y yum-utils"
      - "yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo"
      - "yum -y install terraform"
  build:
    commands:
      - "cd ${CODEBUILD_SRC_DIR}/${CODE_SRC_DIR}"
      - "terraform init"
      - "echo ## TERRAFORM PLAN : Generate the Terraform Plan"
      - "terraform plan -out tfapply"
  post_build:
    commands:
      - "echo Terraform init build completed on `date`"
artifacts:
  files:
    - '**/*'